import { rankBoards, terrainLabels, isWideSize } from './catalog.mjs';
const app=document.querySelector('#app');
const state={boards:[], answers:JSON.parse(sessionStorage.getItem('finderAnswers')||'null')||{ability:'',terrain:'',feel:'',wide:false},step:0};
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>v?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(v):'';
const photo=(p,cls='')=>p.image?`<img class="${cls}" src="${escape(p.image)}" alt="${escape(p.brand+' '+p.model)}" loading="lazy" referrerpolicy="no-referrer" onerror="this.replaceWith(document.createElement('span'))">`:`<div class="photo-fallback">PLAYBOOK<br><small>Image coming soon</small></div>`;
const steps=[
  {key:'ability',title:'Where are you in your riding?',subtitle:'Choose the level that feels most like you.',choices:[['Beginner','Getting comfortable'],['Intermediate','Confident on most runs'],['Advanced','Pushing into harder terrain'],['Expert','At home on demanding lines']]},
  {key:'terrain',title:'Where do you spend most days?',subtitle:'We use the catalog’s terrain ratings to surface strong options.',choices:Object.entries(terrainLabels).map(([v,l])=>[v,l])},
  {key:'feel',title:'What kind of feel sounds right?',subtitle:'This uses each board’s listed flex. You can skip if unsure.',choices:[['playful','Playful & forgiving'],['balanced','A bit of both'],['supportive','Supportive & precise']]},
  {key:'wide',title:'Looking for a wide size?',subtitle:'We can highlight boards with a wide variant. Boot fit still needs an in-person check.',choices:[['false','No preference'],['true','Show wide options']]},
];
async function load(){try{let boards;try{const cfg=await import('./firebase-config.js');if(!cfg.firebaseConfig?.projectId)throw Error('No Firebase project');const [{initializeApp},{getFirestore,collection,getDocs}]=await Promise.all([import('https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js'),import('https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js')]);const db=getFirestore(initializeApp(cfg.firebaseConfig));boards=(await getDocs(collection(db,'customerBoards'))).docs.map(d=>d.data());}catch(e){if(location.hostname!=='localhost'&&location.hostname!=='127.0.0.1')throw e;const r=await fetch('./data/catalog-preview.json');if(!r.ok)throw Error('Preview catalog unavailable');boards=(await r.json()).boards;}state.boards=boards;route();}catch(e){app.innerHTML='<section class="empty"><h1>Catalog unavailable</h1><p>Please try again later.</p></section>';console.error(e)}}
function route(){const path=decodeURIComponent(location.hash.slice(1));if(path.startsWith('/board/'))return detail(path.slice(7));if(path==='/results')return results();if(path==='/find')return question();home()}
function home(){app.innerHTML=`<section class="hero"><div class="hero-copy"><p class="eyebrow">THE RIGHT RIDE STARTS HERE</p><h1>Find your next<br><em>favorite</em> board.</h1><p>Tell us how you ride. We’ll show you snowboards from our current catalog and explain what stands out.</p><a class="button light" href="#/find">Find my board <span>↗</span></a><p class="micro">Four quick questions · No account needed</p></div><div class="hero-art"><span>01 / SNOWBOARDS</span><div class="circle"></div><strong>MADE<br>FOR<br>YOUR<br>LINE.</strong></div></section><section class="intro"><p class="eyebrow">FIND MY GEAR</p><h2>Good gear starts with<br>good questions.</h2><p>We compare your answers with published ability, terrain and flex information. You’ll see actual sizes and setup suggestions on every board page.</p><div class="stat"><strong>${state.boards.length}</strong><span>published boards<br>to explore</span></div></section>`}
function question(){const s=steps[state.step];app.innerHTML=`<section class="finder"><div class="progress"><span>QUESTION ${state.step+1} / ${steps.length}</span><span>${Math.round((state.step+1)/steps.length*100)}%</span></div><div class="progress-bar"><i style="width:${(state.step+1)/steps.length*100}%"></i></div><p class="eyebrow">LET'S FIND YOUR LINE</p><h1>${s.title}</h1><p class="muted">${s.subtitle}</p><div class="choices">${s.choices.map(([v,l])=>`<button class="choice ${String(state.answers[s.key])===v?'selected':''}" data-value="${v}"><span>${escape(l)}</span><b>↗</b></button>`).join('')}</div><div class="finder-actions"><button class="text-button" id="back">${state.step?'← Previous question':'← Start over'}</button>${state.step===2?'<button class="text-button" id="skip">Skip →</button>':''}</div></section>`;app.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{state.answers[s.key]=s.key==='wide'?b.dataset.value==='true':b.dataset.value;sessionStorage.setItem('finderAnswers',JSON.stringify(state.answers));next()});app.querySelector('#back').onclick=()=>{if(state.step)state.step--;else location.hash='/';question()};app.querySelector('#skip')?.addEventListener('click',next)}
function next(){if(state.step<steps.length-1){state.step++;question()}else location.hash='/results'}
function results(){const ranked=rankBoards(state.boards,state.answers);const visible=ranked.filter(x=>x.eligible&&x.score>0);app.innerHTML=`<section class="results-head"><p class="eyebrow">YOUR SHORTLIST</p><h1>Boards worth<br><em>a closer look.</em></h1><p>Ranked by the catalog fields matching your answers. A higher rank is a starting point, not a fit guarantee.</p><div class="result-tools"><span>${visible.length} matching boards</span><a href="#/find" id="restart">Refine answers ↗</a></div></section><section class="cards">${visible.map(({board:b,reasons},i)=>`<a class="card" href="#/board/${encodeURIComponent(b.id)}"><div class="card-image">${photo(b)}<span class="card-number">${String(i+1).padStart(2,'0')}</span></div><div class="card-body"><p class="eyebrow">${escape(b.brand)}</p><h2>${escape(b.model)}</h2><p class="card-spec">${escape([b.shape,b.profile,b.flex&&b.flex+' flex'].filter(Boolean).join(' · '))}</p><div class="reasons">${reasons.map(r=>`<span>${escape(r)}</span>`).join('')}</div><div class="card-foot"><strong>${money(b.price)}</strong><span>View board ↗</span></div></div></a>`).join('')}</section>${visible.length?'':'<section class="empty"><h2>No direct matches yet.</h2><p>Try another terrain or ability to explore more boards.</p></section>'}`;app.querySelector('#restart').onclick=()=>{state.step=0}}
function detail(id){const b=state.boards.find(x=>x.id===id);if(!b){app.innerHTML='<section class="empty"><h1>Board unavailable</h1><a href="#/results">Back to results</a></section>';return}const allImages=b.images?.length?b.images:[{url:b.image,alt:b.model}];const sizes=b.sizes||[];const rank=rankBoards([b],state.answers)[0];const recs=['binding','boot'].map(type=>{const r=b.recommendations?.[type]?.recommended;return r?`<article class="setup-item">${photo(r)}<div><p class="eyebrow">RECOMMENDED ${type.toUpperCase()}</p><h3>${escape(r.brand)} ${escape(r.model)}</h3><p>${money(r.price)}</p></div></article>`:''}).join('');app.innerHTML=`<div class="detail-back"><a href="#/results">← Back to results</a></div><article class="detail"><div class="detail-media">${photo({brand:b.brand,model:b.model,image:allImages[0]?.url})}${allImages.length>1?`<div class="thumbs">${allImages.map((im,i)=>`<button data-img="${escape(im.url)}" aria-label="Show image ${i+1}"><img src="${escape(im.url)}" alt=""></button>`).join('')}</div>`:''}</div><div class="detail-info"><p class="eyebrow">${escape(b.brand)} / SNOWBOARD</p><h1>${escape(b.model)}</h1><div class="price">${money(b.price)}</div><p class="description">${escape(b.description||'More details coming soon.')}</p>${rank.reasons.length?`<div class="why"><h2>Why it surfaced</h2>${rank.reasons.map(r=>`<p>✓ ${escape(r)}</p>`).join('')}</div>`:''}<dl class="specs">${[['Shape',b.shape],['Profile',b.profile],['Flex',b.flex],['Catalog width',b.width]].filter(([,v])=>v).map(([k,v])=>`<div><dt>${k}</dt><dd>${escape(v)}</dd></div>`).join('')}</dl><section class="sizes"><h2>Listed sizes</h2>${sizes.length?`<div class="size-list">${sizes.map(s=>`<span class="${isWideSize(s)?'wide':''}">${escape(s)}${isWideSize(s)?' · wide':''}</span>`).join('')}</div>`:'<p>Sizes have not been listed yet.</p>'}<p class="fine">Listed variants are not live stock or a personalized size recommendation. Confirm sizing and availability in store.</p></section></div></article><section class="setup"><p class="eyebrow">COMPLETE THE RIDE</p><h2>Suggested setup</h2><p>These are the CMS product pairings for this board. Check boot and binding compatibility and fit before purchase.</p><div class="setup-grid">${recs||'<p>No setup recommendations listed yet.</p>'}</div></section>`;app.querySelectorAll('[data-img]').forEach(btn=>btn.onclick=()=>{app.querySelector('.detail-media > img').src=btn.dataset.img})}
window.addEventListener('hashchange',route);load();
